FROM python:3.11-slim

# Set working directory
WORKDIR /mentwai-fastapi

# Install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the FastAPI code
COPY . .

# Start with uvicorn
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
